### ISSUE TITLE
When I build with rollup-plugin-monaco-editor plugin, I get Invalid value for option "output.file" - when building multiple chunks, the "output.dir" option must be used, not "output.file".To inline dynamic imports, set the "inlineDynamicImports" option.

### ISSUE THREAD

**Issue by sunWoodsen** [chengcyber/rollup-plugin-monaco-editor#14]
monaco editor Version: v2.66.1
rollup-plugin-monaco-editor vesion: v0.1.2
Node Version: node v14.18.2

1. **How Do We Reproduce?**

When I build with rollup-plugin-monaco-editor plugin, I get Invalid value for option "output.file" - when building multiple chunks, the "output.dir" option must be used, not "output.file".To inline dynamic imports, set the "inlineDynamicImports" option.
But when I don't build with this plugin, everything is normal, but the build product is very large，
I always set the output property to file, I don't understand why multiple chunks are involved

2. **Expected Behavior**

When using the plugin, the build process works fine and loads on demand.

3. **Actual Behavior**

 I get Invalid value for option "output.file" - when building multiple chunks, the "output.dir" option must be used, not "output.file".To inline dynamic imports, set the "inlineDynamicImports" option.

- this is rollup.config.js

```
import { terser } from 'rollup-plugin-terser';
import typescript from 'rollup-plugin-typescript2';
import monaco from 'rollup-plugin-monaco-editor';
import { visualizer } from 'rollup-plugin-visualizer';
import alias from '@rollup/plugin-alias';
import postcss from 'rollup-plugin-postcss';
import commonjs from '@rollup/plugin-commonjs';
import babel from 'rollup-plugin-babel';
import svgr from '@svgr/rollup';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import path from 'path';
import pkg from './package.json';

const _root = path.resolve(__dirname);

export default {
  input: 'src/index.ts',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      sourcemap: true,
      exports: 'named',
      inlineDynamicImports: true,
    },
    {
      file: pkg.module,
      format: 'esm',
      sourcemap: true,
      exports: 'named',
      inlineDynamicImports: true,
    },
  ],
  plugins: [
    terser(),
    nodeResolve(),
    typescript(),
    visualizer({
      open: true
    }),
    commonjs(),
    babel({
      exclude: 'node_modules/**',
    }),
    monaco({
      languages: ['javascript', 'typescript', 'json', 'css', 'html'],
    }),
    alias({
      resolve: ['.jsx', '.js', '.tsx', 'ts'],
      entries: {
        '@': path.resolve(_root, 'src'),
      },
    }),
    svgr(),
    postcss({
      // extract: true,
      extensions: ['.less', '.css'],
      modules: true,
      use: [['less', { javascriptEnabled: true }]],
    }),
  ],
};
```

**Comment by chengcyber** [comment]
Hi @sunWoodsen , The correct way to use this plugin now is setup `output.dir` instead of `output.file`.

Try this

```
// ...
import pkg from './package.json';

const _root = path.resolve(__dirname);
const mainFile = path.resolve(_root, pkg.main);
const moduleFile = path.resolve(_root, pkg.module);

export default {
  input: "src/index.ts",
  output: [
    {
      // file: pkg.main,
      dir: path.dirname(mainFile),  //  <--- here
      format: "cjs",
      sourcemap: true,
      exports: "named",
      // inlineDynamicImports: true, 
    },
    {
      // file: pkg.module,
      dir: path.dirname(moduleFile), // <--- here
      format: "esm",
      sourcemap: true,
      exports: "named",
      // inlineDynamicImports: true,
    },
  ],
  // ...
}
```


 And, it seems `inlineDynamicImports` is a new feature and kind of buggy...

**Comment by sunWoodsen** [comment]
Hi @chengcyber，I have used dir instead of file before, but I get this error, from the error message I can see that monaco is causing it to happen, but I don't understand the specific reason and how to fix it

![image](https://user-images.githubusercontent.com/39180485/155277456-ecf68c46-60b3-4250-8915-365259bc26d7.png)

**Comment by chengcyber** [comment]
@sunWoodsen I see. It takes me more time to fix the sourcemap correctness. If you don't care about sourcemap, you can go on your work now :)

**Comment by chengcyber** [comment]
🚀 `rollup-plugin-monaco-editor@0.2.1` released
