### ISSUE TITLE
Not found the codicon.ttf

### ISSUE THREAD

**Issue by imguolao** [chengcyber/rollup-plugin-monaco-editor#19]
我按照 README 跑了 example，不过好像少了个字体图标没有被打包出来。
I ran the example according to README, but got the below error.

![image](https://user-images.githubusercontent.com/25502024/174479999-6e1959e0-f984-4e4f-a0ba-be2b2ab4def0.png)

**Comment by imguolao** [comment]
还有另一个小问题，就是 build 这个插件的时候，ts 提示 `Cannot find module 'path' or its corresponding type declarations.`，安装 `@types/node` 后正常。

And has another problem, when executing `pnpm build`, typescript reports an error, after installing `@types/node` it works fine.

![image](https://user-images.githubusercontent.com/25502024/174480517-2aac2836-adb8-437f-bba9-f5a49141fab6.png)

**Comment by chengcyber** [comment]
> 我按照 README 跑了 example，不过好像少了个字体图标没有被打包出来。
> I ran the example according to README, but got the below error.

Q: Missing font file when building example.

A: This is free to you how to bundle font assets with rollup. I have updated the `rollup.config.js` for example in the master branch. You can take a look at https://github.com/chengcyber/rollup-plugin-monaco-editor/commit/cd3dc195c05fc96f60eb3dce0e9c2a4fad970d25

> And has another problem, when executing pnpm build, typescript reports an error, after installing @types/node it works fine.

I can not reproduce the issue in my laptop (Mac OS). But i think it's fine to add `@types/node` as a devDependency. Also, update it into the master branch now.
