### ISSUE TITLE
Support for monaco 0.22.3

### ISSUE THREAD

**Issue by kwesterfeld2** [chengcyber/rollup-plugin-monaco-editor#2]
The feature definition remap is not working for later monaco:
```
[monaco] Could not load (...)/ui/node_modules/monaco-editor/esm/vs/editor/editor.api.js?monaco-features (imported by node_modules/monaco-editor/esm/vs/editor/editor.api.js): Cannot find module 'monaco-editor/esm/vs/editor/contrib/rename/onTypeRename.js'
```

**Comment by vladimirtemnikov** [comment]
Support for 0.24.0 will be appreciated too! :)

**Comment by chengcyber** [comment]
Hi, @kwesterfeld2 @vladimirtemnikov, I refact the internal logic to support more monaco editor versions. 

`rollup-plugin-monaco-editor@0.0.8` now supports `monaco-editor@0.21.*` to `0.25.*`. Plz have a try
