### ISSUE TITLE
can't doc example  run

### ISSUE THREAD

**Issue by kekeon** [chengcyber/rollup-plugin-monaco-editor#8]
ask a question：
![image](https://user-images.githubusercontent.com/20576273/132116900-8a6cfccc-ff15-4927-9c8c-3ad981d538fc.png)

**Comment by chengcyber** [comment]
I borrowed a Windows laptop to run example, but could not reproduce this issue.  (Win 10 with Git Bash).

Everything works fine, here is a screenshot

![image](https://user-images.githubusercontent.com/16147702/132265070-869eff6a-6263-4b4b-853f-bb0db44fc08f.png)

Maybe provide more info to see what else i can help.

**Comment by chengcyber** [comment]
Close now
